sudo: required
language: node_js
node_js:
  - "10.5.0"

addons:
  chrome: stable

before_install:
  - pip install --user awscli
  - npm install -g npm@latest

before_script:
  - npm install -g @angular/cli
  - npm install -g webpack
  - npm install nsp -g
  - npm install

script:
  - ng lint
  - ng test --browser=ChomeHeadless --watch=false --code-coverage --sm=false
  - ng build --prod

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  on:
    branch: master
  provider: s3
  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  # Name of the S3 bucket to which your site should be uploaded.
  bucket: lakin-financial
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  # Path to a directory containing your built site.
  local_dir: dist
  # Set the Cache-Control header.
  cache_control: "max-age=21600"
